### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by mattn**
Most of icons does not displayed on Windows Terminal. But it can be solved with another fonts.

image

### CODE REVIEW

**Comment by Yash-Handa** [comment]
Thanks very much for the Pull Request, it looks awesome :)

Just one query though,
Is the `go-colorable` package required for providing true colors on Windows cmd/powershell. I mean does an ASCII escape sequence not work in windows like `\033[38;2;125;125;125m` or are there some edge cases ?

For your font issue use [Nerd-Fonts](https://github.com/ryanoasis/nerd-fonts), this [comment](https://github.com/Yash-Handa/logo-ls/issues/4#issuecomment-697067129) has more info regarding it.

**Comment by Starz0r** [comment]
The default PowerShell v5 terminal doesn't have proper ASCII escapes, so the only way to support that is through a package like `go-colorable`. I believe PowerShell v6 and onwards has native support but I'm unsure, you should mostly rely on terminal implementations that do have it like Windows Terminal or Alacritty.

**Comment by Starz0r** [comment]
@Yash-Handa The default PowerShell v5 terminal doesn't have proper ASCII escapes, so the only way to support that is through a package like `go-colorable`. I believe PowerShell v6 and onwards has native support but I'm unsure, you should mostly rely on terminal implementations that do have it like Windows Terminal or Alacritty.

**Review by Yash-Handa — APPROVED** [review]

**Comment by Yash-Handa** [comment]
Thanks @mattn, For such an awesome PR : )

**Pull request merged**
