### PR TITLE
Add AUR badge

### PR DESCRIPTION
**Pull request by JojiiOfficial**
I created an AUR package for logo-ls. Here is the badge for it!

### CODE REVIEW

**Comment by Yash-Handa** [comment]
Hi @JojiiOfficial,

Thanks for the AUR package :)

I don't know how AURs works so could you tell how this package will be updated, that is, if a new **GitHub release** is made will the AUR package automatically update or some pipe line has to be setup in order to update the AUR package.

Second, could you please tell how to use  this AUR package, this info will be presented in the README of the project under Installation section.

The above questions can be too naive ;)

**Comment by JojiiOfficial** [comment]
The package must be updated manually. I can add you as co-maintainer to the AUR package (for this you need an account on aur.archlinux.org). Then you can update it using CI/CD. Otherwise I'll update the package version for each new gh release as long as I maintain the package.

To install it on arch/arch based distributions, you need an AUR helper like yay. 
If you desire so, I can add a section describing those steps to the REDAME and push it to this PR.

**Comment by Yash-Handa** [comment]
Ohh, in that case, please add me to the AUR package (though I would mostly assign you an issue if any updates are to be made).
my AUR account username: Yash-Handa

Feel free to update the README.md for instructions on how to use the AUR package :)

**Comment by JojiiOfficial** [comment]
I am watching this repository for releases so mostly you don't need to notify me. In case I don't update the package within a dev days, feel free to contact me.

**Comment by JojiiOfficial** [comment]
@Yash-Handa Unless you have something to add, the README is ready to get merged!

**Comment by Yash-Handa** [comment]
Thanks for the Pull Request. I am merging it : )

**Pull request merged**
